stages:
  - build

before_script:
  - before_ci_script

docker-build:
  stage: build
  script:
    - docker_build_script
  after_script:
    - after_ci_script
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^ci /
#测试阶段先放开，要不ship部署有时因为bug每次都得手动编译
      - $CI_COMMIT_REF_NAME == "master"
      - $CI_PIPELINE_SOURCE == "web"
      - $CI_PIPELINE_SOURCE == "api"
  tags:
    - global-runner